# Generated by Django 4.1.5 on 2023-02-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tut_apl', '0006_attendance_attendancereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='admin',
        ),
        migrations.DeleteModel(
            name='AttendanceReport',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
